---

- name: Create eda credential
  infra.eda_configuration.credential:
    name: "{{ configuration_automationeda_credential.0.name }}"
    username: "{{ configuration_automationeda_credential.0.username }}"
    secret: "{{ configuration_automationeda_credential.0.password }}"
    credential_type: "{{ configuration_automationeda_credential.0.eda_type }}"
    state: "{{ state }}"
    eda_host: "{{ eda_host }}"
    eda_username: "{{ eda_username }}"
    eda_password: "{{ eda_password }}"
    validate_certs: "{{ validate_certs }}"
    description: "{{ description_project }}"

