---
- name: Criando executions execution environment repo
  with_subelements:
    - "{{ config_hub_name_of_execution_environments }}"
    - images
  infra.ah_configuration.ah_ee_repository:
    ah_host: "{{ config_hub_automationhub_url }}"
    ah_username: "{{ config_hub_automationhub_username }}"
    ah_password: "{{ config_hub_automationhub_password }}"
    validate_certs: "{{ validate_certs | default('false') }}"
    name: "{{ item.1.upstream_name.split('/')[1] }}"
    upstream_name: "{{ item.1.upstream_name }}"
    registry: "{{ item.0.name }}"
    include_tags: "{{ item.1.tag }}"
    state: "{{ config_aap_estado }}"
...