---
- name: Ensure execution environment the namespace exists
  infra.ah_configuration.ah_ee_namespace:
    ah_host: "{{ config_hub_automationhub_url }}"
    ah_username: "{{ config_hub_automationhub_username }}"
    ah_password: "{{ config_hub_automationhub_password }}"
    validate_certs: "{{ validate_certs | default('false') }}"
    name: ansible-automation-platform-20-early-access
    state: "{{ config_aap_estado }}"
...