---
- name: Criando executions execution environment registry
  loop: "{{ config_hub_name_of_execution_environments }}"
  infra.ah_configuration.ah_ee_registry:
    ah_host: "{{ config_hub_automationhub_url }}"
    ah_username: "{{ config_hub_automationhub_username }}"
    ah_password: "{{ config_hub_automationhub_password }}"
    validate_certs: "{{ validate_certs | default('false') }}"
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    url: "{{ item.url }}"
    username: "{{ item.username | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    
...