---
- name: Sincronizando as collections
  loop: "{{ config_hub_name_of_collection_repositories }}"
  when:
  - ( item.sync is defined )
  - ( item.sync is true )
  infra.ah_configuration.collection_repository_sync:
    ah_host: "{{ config_hub_automationhub_url }}"
    ah_username: "{{ config_hub_automationhub_username }}"
    ah_password: "{{ config_hub_automationhub_password }}"
    validate_certs: "{{ validate_certs | default('false') }}"
    name: "{{ item.name }}"
    wait: true
    timeout: 1200
  retries: 30
...
