---
- name: Criando collections repos
  loop: "{{ config_hub_name_of_collection_repositories }}"
  infra.ah_configuration.collection_repository:
    ah_host: "{{ config_hub_automationhub_url }}"
    ah_username: "{{ config_hub_automationhub_username }}"
    ah_password: "{{ config_hub_automationhub_password }}"
    validate_certs: "{{ validate_certs | default('false') }}"
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    pulp_labels:
      pipeline: "{{ item.pulp_labels.pipeline }}"
    distribution:
      state: "{{ item.distribution.state }}"
    remote: "{{ item.remote }}"
...
