---
- name: Criando collections remotes
  loop: "{{ config_hub_name_of_collection_remotes }}"
  infra.ah_configuration.collection_remote:
    ah_host: "{{ config_hub_automationhub_url }}"
    ah_username: "{{ config_hub_automationhub_username }}"
    ah_password: "{{ config_hub_automationhub_password }}"
    validate_certs: "{{ validate_certs | default('false') }}"
    name: "{{ item.name }}"
    url: "{{ item.url }}"
    requirements: "{{ item.requirements | default(omit) }}"
    token: "{{ item.token | default(omit) }}"
    auth_url: "{{ item.auth_url | default(omit) }}"
...
